[471652] Can't perform setup tasks on Linux because of NoSuchMethodError and InvocationTargetException
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471652